# Generated by Django 4.0.3 on 2022-04-06 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='QUESTION ID')),
                ('question', models.CharField(max_length=1024, verbose_name='QUESTION')),
                ('A', models.CharField(max_length=128)),
                ('B', models.CharField(max_length=128)),
                ('C', models.CharField(max_length=128)),
                ('D', models.CharField(max_length=128)),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B', 'B'), ('B', 'B')], max_length=1, verbose_name='Correct Choice')),
                ('difficulty', models.CharField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD')], max_length=1, verbose_name='Difficulty Level')),
            ],
        ),
        migrations.CreateModel(
            name='CN',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Test.question')),
            ],
            bases=('Test.question',),
        ),
        migrations.CreateModel(
            name='DBMS',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Test.question')),
            ],
            bases=('Test.question',),
        ),
        migrations.CreateModel(
            name='JAVA',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Test.question')),
            ],
            bases=('Test.question',),
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Test.question')),
            ],
            bases=('Test.question',),
        ),
        migrations.CreateModel(
            name='PYTHON',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Test.question')),
            ],
            bases=('Test.question',),
        ),
    ]
