# Generated by Django 4.0.3 on 2022-04-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cn',
            options={'verbose_name_plural': 'CN'},
        ),
        migrations.AlterModelOptions(
            name='dbms',
            options={'verbose_name_plural': 'DBMS'},
        ),
        migrations.AlterModelOptions(
            name='java',
            options={'verbose_name_plural': 'JAVA'},
        ),
        migrations.AlterModelOptions(
            name='os',
            options={'verbose_name_plural': 'OS'},
        ),
        migrations.AlterModelOptions(
            name='python',
            options={'verbose_name_plural': 'PYTHON'},
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profiles.student')),
            ],
        ),
    ]
