# Generated by Django 4.0.3 on 2022-04-10 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('OS', 'OS'), ('DBMS', 'DBMS'), ('CN', 'CN')], default='JAVA', max_length=32, verbose_name='Subject')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('date', models.DateField(auto_now=True)),
                ('r_1', models.CharField(max_length=1, null=True)),
                ('r_2', models.CharField(max_length=1, null=True)),
                ('r_3', models.CharField(max_length=1, null=True)),
                ('r_4', models.CharField(max_length=1, null=True)),
                ('r_5', models.CharField(max_length=1, null=True)),
                ('r_6', models.CharField(max_length=1, null=True)),
                ('r_7', models.CharField(max_length=1, null=True)),
                ('r_8', models.CharField(max_length=1, null=True)),
                ('r_9', models.CharField(max_length=1, null=True)),
                ('r_10', models.CharField(max_length=1, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profiles.student')),
            ],
        ),
    ]
