# Generated by Django 4.0.3 on 2022-04-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_cache_a_cache_b_cache_c_cache_d_cache_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='qid',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
