# Generated by Django 4.0.3 on 2022-04-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_result_responses_result_subject_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
