# Generated by Django 4.0.3 on 2022-04-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_cache_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD')], default=1),
        ),
    ]
