# Generated by Django 4.0.3 on 2022-04-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_alter_cache_r_1_alter_cache_r_10_alter_cache_r_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='CACHE ID'),
        ),
    ]
